CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nama_institusi TEXT,
  alamat TEXT,
  kota TEXT,
  provinsi TEXT,
  cp TEXT,
  no_telepon TEXT,
  e_mail TEXT,
  categories_1 TEXT,
  categories_2 TEXT
);