-- CLEAN SLATE SCRIPT (Resets everything)
-- Use CASCADE to ensure related policies and objects are also removed
DROP TABLE IF EXISTS clients CASCADE;

CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nama_institusi TEXT,
  alamat TEXT,
  kota TEXT,
  provinsi TEXT,
  cp TEXT,
  no_telepon TEXT,
  e_mail TEXT,
  categories_1 TEXT,
  categories_2 TEXT
);

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON clients;
DROP POLICY IF EXISTS "Enable insert access for all users" ON clients;
DROP POLICY IF EXISTS "Enable update access for all users" ON clients;

-- Only authenticated users can read, insert, and update
CREATE POLICY "Enable read access for all users" ON clients FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable insert access for all users" ON clients FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update access for all users" ON clients FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');